### ISSUE TITLE
Plugins work only with webpack v4.x

### ISSUE THREAD

**Issue by ernscht** [merkle-open/webpack-config-plugins#91]
It is not clear that the plugins currently only work with webpack v4.x
We should document this with right compatibility ranges in peerDependencies

Plugin version: 2.0.2

(The webpack 5 update is discussed here: #68)

**Comment by oliverdietsche** [comment]
PR: https://github.com/merkle-open/webpack-config-plugins/pull/104

**Comment by ernscht** [comment]
merged
